"""
app.py
Streamlit FAQ chatbot — OpenAI + FAISS RAG
Run: streamlit run app.py
"""

import os
import base64
import datetime
import requests
import streamlit as st
from dotenv import load_dotenv
from openai import OpenAI

import rag_engine

load_dotenv()

# ── Demo mode (no API key needed) ─────────────────────────────────────────────
DEMO_MODE = True

CANNED_RESPONSES = [
    "This is a demo response. In production, this would be answered using your FAQ document via OpenAI.",
    "Demo mode active — I'm returning a canned answer. Add your OpenAI API key to get real responses.",
    "Great question! (Demo) In real mode, I would search your FAQ and generate a grounded answer.",
    "I found some relevant context in your FAQ. (Demo) This answer would normally be generated by gpt-4o-mini.",
]


def get_base64_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode()


_bg = get_base64_image(os.path.join(os.path.dirname(__file__), "assets", "hero.jpg"))

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Virtual Pro — FAQ Assistant",
    page_icon="🤖",
    layout="centered",
)

# ── Custom CSS ─────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap');

html, body, [class*="css"] {{
    font-family: 'Open Sans', sans-serif;
}}

/* hide default streamlit chrome */
#MainMenu, footer, header {{ visibility: hidden; }}

html, body, .stApp {{
    background-image:
        linear-gradient(135deg, rgba(6,6,103,0.82) 0%, rgba(0,58,140,0.75) 50%, rgba(0,162,255,0.45) 100%),
        url("data:image/jpeg;base64,{_bg}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-color: #060667;
    min-height: 100vh;
    color: #ffffff;
}}

/* sidebar */
[data-testid="stSidebar"] {{
    background: linear-gradient(180deg, #060667 0%, #003a8c 100%);
    border-right: 1px solid #00A2FF44;
}}
[data-testid="stSidebar"] * {{ color: #e0f4ff !important; }}

/* sidebar headings */
[data-testid="stSidebar"] h2,
[data-testid="stSidebar"] h3 {{
    color: #00A2FF !important;
}}

/* chat messages — assistant */
[data-testid="stChatMessage"] {{
    background: rgba(255, 255, 255, 0.92);
    border: 1px solid #00A2FF88;
    border-radius: 12px;
    margin-bottom: 8px;
    padding: 4px 8px;
    color: #060667;
}}

/* chat messages — user */
[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) {{
    border-color: #00A2FF;
    background: rgba(255, 255, 255, 0.95);
    color: #060667;
}}

/* input bar */
[data-testid="stChatInput"] textarea {{
    background: #ffffff !important;
    border: 1px solid #00A2FF !important;
    border-radius: 10px !important;
    color: #060667 !important;
    font-family: 'Open Sans', sans-serif !important;
}}
[data-testid="stChatInput"] textarea:focus {{
    box-shadow: 0 0 0 2px #00A2FF55 !important;
}}

/* buttons */
.stButton > button {{
    background: linear-gradient(to right, #060667, #00A2FF);
    color: #fff;
    border: 2px solid #ffffff33;
    border-radius: 8px;
    font-family: 'Open Sans', sans-serif;
    font-weight: 600;
    width: 100%;
    padding: 0.5rem;
    transition: all 0.2s;
}}
.stButton > button:hover {{
    background: linear-gradient(to right, #00A2FF, #060667);
    color: #ff8c00;
    border-color: #ff8c00;
}}

/* source expander */
.streamlit-expanderHeader {{
    font-size: 12px !important;
    color: #00A2FF !important;
}}

/* status badges */
.badge {{
    display: inline-block;
    padding: 2px 10px;
    border-radius: 100px;
    font-size: 12px;
    font-weight: 600;
    font-family: 'Open Sans', sans-serif;
}}
.badge-green {{ background: #003a1a; color: #00e676; border: 1px solid #00A2FF55; }}
.badge-red   {{ background: #3a0006; color: #ff5252; border: 1px solid #ff525255; }}
</style>
""", unsafe_allow_html=True)

# ── Session state ──────────────────────────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []
if "index" not in st.session_state:
    st.session_state.index = None
if "chunks" not in st.session_state:
    st.session_state.chunks = None
if "n8n_webhook_url" not in st.session_state:
    st.session_state.n8n_webhook_url = (
        os.getenv("N8N_WEBHOOK_URL")
        or st.secrets.get("N8N_WEBHOOK_URL", "")
    )


# ── Helpers ────────────────────────────────────────────────────────────────────
def try_load_index():
    """Attempt to load an existing index from disk silently."""
    try:
        idx, chunks = rag_engine.load_index()
        st.session_state.index = idx
        st.session_state.chunks = chunks
        return True
    except FileNotFoundError:
        return False


def index_ready() -> bool:
    return st.session_state.index is not None and st.session_state.chunks is not None


def send_to_n8n(question: str, answer: str, sources: list[str]) -> None:
    """Fire-and-forget POST to the configured n8n webhook URL.

    Sends question, answer, sources, and a UTC timestamp so n8n can
    route the data into Google Sheets (or any other node).
    Silently swallows errors so a webhook failure never breaks the chat.
    """
    webhook_url = st.session_state.get("n8n_webhook_url", "").strip()
    if not webhook_url:
        return
    payload = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "question": question,
        "answer": answer,
        "sources": sources,
    }
    try:
        requests.post(webhook_url, json=payload, timeout=5)
    except Exception:
        pass


def answer_question(question: str) -> tuple[str, list[str]]:
    """Retrieve context and call OpenAI to generate a grounded answer."""
    if DEMO_MODE:
        result = rag_engine.search_faqs_json(question)
        if result:
            matched_q, answer = result
            source = f"**Q:** {matched_q}"
        else:
            answer = "Sorry, I couldn't find a matching answer in the FAQ."
            source = "(No match found)"
        placeholder = st.empty()
        placeholder.markdown(answer)
        return answer, [source]

    client = rag_engine.get_client()
    context_chunks = rag_engine.retrieve(
        question, st.session_state.index, st.session_state.chunks
    )
    context_text = "\n\n---\n\n".join(context_chunks)

    system_prompt = (
        "You are a helpful FAQ assistant. Answer the user's question using ONLY "
        "the context provided below. If the answer is not in the context, say so "
        "honestly — do not make up information.\n\n"
        f"CONTEXT:\n{context_text}"
    )

    history = [{"role": m["role"], "content": m["content"]}
               for m in st.session_state.messages[-8:]]  # last 4 turns

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "system", "content": system_prompt}, *history,
                  {"role": "user", "content": question}],
        temperature=0.2,
        max_tokens=150,
        stream=True,
    )

    full_response = ""
    placeholder = st.empty()
    for chunk in response:
        delta = chunk.choices[0].delta.content or ""
        full_response += delta
        placeholder.markdown(full_response + "▌")
    placeholder.markdown(full_response)

    return full_response, context_chunks


# ── Load existing index on first run ──────────────────────────────────────────
if not index_ready():
    try_load_index()

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## ⚙️ Setup")

    api_key_input = st.text_input(
        "OpenAI API Key",
        type="password",
        placeholder="sk-...",
        value=os.getenv("OPENAI_API_KEY") or st.secrets.get("OPENAI_API_KEY", ""),
    )
    if api_key_input:
        os.environ["OPENAI_API_KEY"] = api_key_input

    st.markdown("---")
    st.markdown("### 🔗 n8n Webhook")
    webhook_input = st.text_input(
        "Webhook URL",
        placeholder="https://your-n8n.com/webhook/...",
        value=st.session_state.n8n_webhook_url,
    )
    if webhook_input != st.session_state.n8n_webhook_url:
        st.session_state.n8n_webhook_url = webhook_input

    if st.session_state.n8n_webhook_url:
        st.markdown(
            '<span class="badge badge-green">● Webhook active</span>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<span class="badge badge-red">● No webhook set</span>',
            unsafe_allow_html=True,
        )

    st.markdown("---")
    st.markdown("### 📄 FAQ Document")

    uploaded = st.file_uploader("Upload your FAQ (.txt)", type=["txt"])
    if uploaded:
        with open("faqs.txt", "wb") as f:
            f.write(uploaded.getbuffer())
        st.success("File saved as faqs.txt")

    if st.button("🔨 Build / Rebuild Index"):
        if DEMO_MODE:
            st.info("Demo mode — index not needed. Just start chatting!")
        elif not os.getenv("OPENAI_API_KEY"):
            st.error("Enter your API key first.")
        else:
            with st.spinner("Embedding and indexing…"):
                try:
                    idx, chunks = rag_engine.build_index("faqs.txt")
                    st.session_state.index = idx
                    st.session_state.chunks = chunks
                    st.success(f"✅ Indexed {len(chunks)} chunks")
                except Exception as e:
                    st.error(f"Error: {e}")

    st.markdown("---")

    # Status indicator
    if index_ready():
        n = len(st.session_state.chunks)
        st.markdown(
            f'<span class="badge badge-green">● Index ready — {n} chunks</span>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<span class="badge badge-red">● No index — build one above</span>',
            unsafe_allow_html=True,
        )

    st.markdown("---")
    st.markdown("### 💬 Conversation")
    if st.button("🗑️ Clear chat"):
        st.session_state.messages = []
        st.rerun()

    st.markdown("""
    <div style="margin-top:2rem;font-size:11px;color:#00A2FF;line-height:1.8">
    <b style="color:#ffffff">Virtual Pro Software Development</b><br>
    virtualproph.com<br><br>
    <span style="color:#88aacc">Streamlit · OpenAI gpt-4o-mini<br>
    text-embedding-3-small · FAISS</span>
    </div>
    """, unsafe_allow_html=True)

# ── Main chat area ─────────────────────────────────────────────────────────────
st.markdown(
    "<div style='text-align:center;margin-bottom:0.5rem'>"
    "<span style='font-size:13px;font-weight:600;letter-spacing:2px;color:#00A2FF;text-transform:uppercase'>Virtual Pro</span>"
    "</div>"
    "<h2 style='text-align:center;color:#ffffff;font-weight:700;font-family:Open Sans,sans-serif;"
    "margin-bottom:0.25rem'>FAQ Assistant</h2>",
    unsafe_allow_html=True,
)
st.markdown(
    "<p style='text-align:center;color:#00A2FF;font-size:14px;margin-bottom:1.5rem'>"
    "Cost-effective &amp; reliable answers — grounded in your FAQ document.</p>",
    unsafe_allow_html=True,
)

# Render history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            with st.expander(f"📎 {len(msg['sources'])} source chunks used"):
                for i, src in enumerate(msg["sources"], 1):
                    st.markdown(
                        f"<div style='font-size:12px;color:#888;padding:6px 0;"
                        f"border-top:1px solid #2a2a30'><b>#{i}</b><br>{src}</div>",
                        unsafe_allow_html=True,
                    )

# Chat input
if prompt := st.chat_input("Ask a question about our FAQ…"):
    if not DEMO_MODE and not os.getenv("OPENAI_API_KEY"):
        st.error("Add your OpenAI API key in the sidebar.")
    elif not DEMO_MODE and not index_ready():
        st.error("Build the index first using the sidebar.")
    else:
        # Show user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate and show assistant response
        with st.chat_message("assistant"):
            try:
                answer, sources = answer_question(prompt)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": answer,
                    "sources": sources,
                })
                send_to_n8n(prompt, answer, sources)
                if sources:
                    with st.expander(f"📎 {len(sources)} source chunks used"):
                        for i, src in enumerate(sources, 1):
                            st.markdown(
                                f"<div style='font-size:12px;color:#888;padding:6px 0;"
                                f"border-top:1px solid #2a2a30'><b>#{i}</b><br>{src}</div>",
                                unsafe_allow_html=True,
                            )
            except Exception as e:
                st.error(f"Error: {e}")
