"""
app.py
======
Streamlit web interface for the Virtual Pro FAQ Chatbot.

This module is the application entry point. It wires together the Streamlit UI
with the RAG engine (``rag_engine.py``) and the OpenAI Chat API to deliver an
interactive FAQ assistant.

Usage
-----
    streamlit run app.py

Environment
-----------
``OPENAI_API_KEY``
    Your OpenAI secret key. Can be set in ``.env`` or entered at runtime via
    the sidebar. Required when ``DEMO_MODE = False``.

Modes
-----
DEMO_MODE = True  (default)
    No API key needed. Queries are answered by a keyword-overlap search
    against ``faqs.json``. Responses are instant (no streaming).

DEMO_MODE = False
    Full RAG pipeline: the FAQ file is embedded with ``text-embedding-3-small``,
    stored in a FAISS index, and answers are generated by ``gpt-4o-mini``
    with streaming output.

Session State Keys
------------------
messages : list[dict]
    Chat history. Each entry has keys ``"role"`` (``"user"`` | ``"assistant"``),
    ``"content"`` (str), and optionally ``"sources"`` (list[str]) for assistant
    messages.
index : faiss.Index | None
    The loaded FAISS vector index. ``None`` until an index is built or loaded.
chunks : list[str] | None
    The list of raw FAQ text chunks parallel to the index vectors. ``None``
    until populated.
"""

import os
import base64
import streamlit as st
from dotenv import load_dotenv

import rag_engine

# Load OPENAI_API_KEY (and any other vars) from .env into os.environ
load_dotenv()

# ── Mode flag ──────────────────────────────────────────────────────────────────
# Set to False (and provide OPENAI_API_KEY) for full RAG + GPT responses.
DEMO_MODE = True

# Rotating canned replies used when DEMO_MODE is True and no FAQ match is found.
CANNED_RESPONSES = [
    "This is a demo response. In production, this would be answered using your FAQ document via OpenAI.",
    "Demo mode active — I'm returning a canned answer. Add your OpenAI API key to get real responses.",
    "Great question! (Demo) In real mode, I would search your FAQ and generate a grounded answer.",
    "I found some relevant context in your FAQ. (Demo) This answer would normally be generated by gpt-4o-mini.",
]


# ── Utility ────────────────────────────────────────────────────────────────────

def get_base64_image(image_path: str) -> str:
    """Read an image file and return its Base64-encoded string.

    Used to embed the hero background image directly in the CSS ``<style>``
    block so no additional static file serving is required by Streamlit.

    Args:
        image_path: Absolute or relative path to the image file.

    Returns:
        A Base64-encoded UTF-8 string suitable for use in a CSS
        ``url("data:image/jpeg;base64,...")`` declaration.

    Raises:
        FileNotFoundError: If *image_path* does not exist.
    """
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode()


# Encode the hero image once at module load time (cached for the session).
_bg = get_base64_image(os.path.join(os.path.dirname(__file__), "assets", "hero.jpg"))

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Virtual Pro — FAQ Assistant",
    page_icon="🤖",
    layout="centered",
)

# ── Custom CSS ─────────────────────────────────────────────────────────────────
# Injected once into the page head. Uses the base64-encoded hero image as the
# background, applies the Open Sans font, and styles all major UI elements.
st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap');

html, body, [class*="css"] {{
    font-family: 'Open Sans', sans-serif;
}}

/* hide default streamlit chrome */
#MainMenu, footer, header {{ visibility: hidden; }}

html, body, .stApp {{
    background-image:
        linear-gradient(135deg, rgba(6,6,103,0.82) 0%, rgba(0,58,140,0.75) 50%, rgba(0,162,255,0.45) 100%),
        url("data:image/jpeg;base64,{_bg}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-color: #060667;
    min-height: 100vh;
    color: #ffffff;
}}

/* sidebar */
[data-testid="stSidebar"] {{
    background: linear-gradient(180deg, #060667 0%, #003a8c 100%);
    border-right: 1px solid #00A2FF44;
}}
[data-testid="stSidebar"] * {{ color: #e0f4ff !important; }}

/* sidebar headings */
[data-testid="stSidebar"] h2,
[data-testid="stSidebar"] h3 {{
    color: #00A2FF !important;
}}

/* chat messages — assistant */
[data-testid="stChatMessage"] {{
    background: rgba(255, 255, 255, 0.92);
    border: 1px solid #00A2FF88;
    border-radius: 12px;
    margin-bottom: 8px;
    padding: 4px 8px;
    color: #060667;
}}

/* chat messages — user */
[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) {{
    border-color: #00A2FF;
    background: rgba(255, 255, 255, 0.95);
    color: #060667;
}}

/* input bar */
[data-testid="stChatInput"] textarea {{
    background: #ffffff !important;
    border: 1px solid #00A2FF !important;
    border-radius: 10px !important;
    color: #060667 !important;
    font-family: 'Open Sans', sans-serif !important;
}}
[data-testid="stChatInput"] textarea:focus {{
    box-shadow: 0 0 0 2px #00A2FF55 !important;
}}

/* buttons */
.stButton > button {{
    background: linear-gradient(to right, #060667, #00A2FF);
    color: #fff;
    border: 2px solid #ffffff33;
    border-radius: 8px;
    font-family: 'Open Sans', sans-serif;
    font-weight: 600;
    width: 100%;
    padding: 0.5rem;
    transition: all 0.2s;
}}
.stButton > button:hover {{
    background: linear-gradient(to right, #00A2FF, #060667);
    color: #ff8c00;
    border-color: #ff8c00;
}}

/* source expander */
.streamlit-expanderHeader {{
    font-size: 12px !important;
    color: #00A2FF !important;
}}

/* status badges */
.badge {{
    display: inline-block;
    padding: 2px 10px;
    border-radius: 100px;
    font-size: 12px;
    font-weight: 600;
    font-family: 'Open Sans', sans-serif;
}}
.badge-green {{ background: #003a1a; color: #00e676; border: 1px solid #00A2FF55; }}
.badge-red   {{ background: #3a0006; color: #ff5252; border: 1px solid #ff525255; }}
</style>
""", unsafe_allow_html=True)

# ── Session state initialisation ───────────────────────────────────────────────
# Streamlit re-runs the entire script on every interaction. Session state
# persists across re-runs within the same browser session.
if "messages" not in st.session_state:
    st.session_state.messages = []   # Full chat history
if "index" not in st.session_state:
    st.session_state.index = None    # FAISS index object (loaded on demand)
if "chunks" not in st.session_state:
    st.session_state.chunks = None   # Parallel text chunks list


# ── Helper functions ───────────────────────────────────────────────────────────

def try_load_index() -> bool:
    """Silently attempt to load a pre-built index from disk into session state.

    Called once on the first page render so a previously built index is
    immediately available without the user clicking "Build Index" again.

    Side effects:
        Sets ``st.session_state.index`` and ``st.session_state.chunks`` on
        success.

    Returns:
        ``True`` if the index was loaded successfully, ``False`` if the index
        files do not exist yet (i.e. :func:`rag_engine.build_index` has never
        been run in the current working directory).
    """
    try:
        idx, chunks = rag_engine.load_index()
        st.session_state.index = idx
        st.session_state.chunks = chunks
        return True
    except FileNotFoundError:
        return False


def index_ready() -> bool:
    """Return ``True`` if both the FAISS index and chunk list are loaded.

    A convenience guard used before calling :func:`answer_question` in
    production mode to avoid ``AttributeError`` on ``None``.

    Returns:
        ``True`` when ``st.session_state.index`` and
        ``st.session_state.chunks`` are both non-``None``.
    """
    return st.session_state.index is not None and st.session_state.chunks is not None


def answer_question(question: str) -> tuple[str, list[str]]:
    """Generate an answer for *question* and stream it into the Streamlit UI.

    Behaviour differs by mode:

    Demo mode (``DEMO_MODE = True``)
        Delegates to :func:`rag_engine.search_faqs_json`. The best-matching
        FAQ entry is displayed instantly (no streaming). Returns the matched
        answer and a one-element source list containing the matched question.

    Production mode (``DEMO_MODE = False``)
        1. Retrieves the top-``TOP_K`` FAQ chunks via FAISS nearest-neighbour
           search (:func:`rag_engine.retrieve`).
        2. Builds a system prompt that instructs ``gpt-4o-mini`` to answer
           **only** from the retrieved context.
        3. Sends the last 4 conversation turns (8 messages) as chat history
           so the model has conversational context without consuming excessive
           tokens.
        4. Streams the response token-by-token into a ``st.empty()``
           placeholder, appending ``"▌"`` as a live typing cursor.

    Args:
        question: The user's raw question string from the chat input.

    Returns:
        A ``(answer, sources)`` tuple where *answer* is the full response
        text and *sources* is a list of the FAQ chunk strings that were used
        as context (or the matched question in demo mode).

    Raises:
        ValueError:        If ``OPENAI_API_KEY`` is not set (production mode).
        openai.OpenAIError: On any API failure.
    """
    if DEMO_MODE:
        result = rag_engine.search_faqs_json(question)
        if result:
            matched_q, answer = result
            source = f"**Q:** {matched_q}"
        else:
            answer = "Sorry, I couldn't find a matching answer in the FAQ."
            source = "(No match found)"
        # Render immediately (no streaming in demo mode)
        placeholder = st.empty()
        placeholder.markdown(answer)
        return answer, [source]

    # ── Production mode ────────────────────────────────────────────────────
    client = rag_engine.get_client()

    # Step 1: retrieve the top-K most relevant FAQ chunks for this query
    context_chunks = rag_engine.retrieve(
        question, st.session_state.index, st.session_state.chunks
    )
    # Join chunks with a visible separator so the model can distinguish them
    context_text = "\n\n---\n\n".join(context_chunks)

    # Step 2: build the grounding system prompt
    system_prompt = (
        "You are a helpful FAQ assistant. Answer the user's question using ONLY "
        "the context provided below. If the answer is not in the context, say so "
        "honestly — do not make up information.\n\n"
        f"CONTEXT:\n{context_text}"
    )

    # Step 3: include the last 4 turns (= 8 messages) of conversation history
    history = [
        {"role": m["role"], "content": m["content"]}
        for m in st.session_state.messages[-8:]
    ]

    # Step 4: call the Chat API with streaming enabled
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            *history,
            {"role": "user", "content": question},
        ],
        temperature=0.2,   # Low temperature keeps answers factual and consistent
        max_tokens=150,    # FAQ answers are typically short
        stream=True,
    )

    # Step 5: accumulate tokens and update the placeholder on each delta
    full_response = ""
    placeholder = st.empty()
    for chunk in response:
        delta = chunk.choices[0].delta.content or ""
        full_response += delta
        placeholder.markdown(full_response + "▌")  # ▌ acts as a live cursor

    # Final render without the cursor
    placeholder.markdown(full_response)

    return full_response, context_chunks


# ── Boot: load existing index on first render ─────────────────────────────────
# Streamlit re-runs this file on every interaction, but session_state persists
# within a session, so this only triggers a disk read on the very first run.
if not index_ready():
    try_load_index()

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## ⚙️ Setup")

    # API key input — pre-populated from .env if available
    api_key_input = st.text_input(
        "OpenAI API Key",
        type="password",
        placeholder="sk-...",
        value=os.getenv("OPENAI_API_KEY", ""),
    )
    if api_key_input:
        # Write back into the environment so rag_engine.get_client() picks it up
        os.environ["OPENAI_API_KEY"] = api_key_input

    st.markdown("---")
    st.markdown("### 📄 FAQ Document")

    # File uploader — overwrites faqs.txt so build_index() always reads fresh data
    uploaded = st.file_uploader("Upload your FAQ (.txt)", type=["txt"])
    if uploaded:
        with open("faqs.txt", "wb") as f:
            f.write(uploaded.getbuffer())
        st.success("File saved as faqs.txt")

    if st.button("🔨 Build / Rebuild Index"):
        if DEMO_MODE:
            st.info("Demo mode — index not needed. Just start chatting!")
        elif not os.getenv("OPENAI_API_KEY"):
            st.error("Enter your API key first.")
        else:
            with st.spinner("Embedding and indexing…"):
                try:
                    idx, chunks = rag_engine.build_index("faqs.txt")
                    st.session_state.index = idx
                    st.session_state.chunks = chunks
                    st.success(f"✅ Indexed {len(chunks)} chunks")
                except Exception as e:
                    st.error(f"Error: {e}")

    st.markdown("---")

    # Index status badge — green when ready, red when not
    if index_ready():
        n = len(st.session_state.chunks)
        st.markdown(
            f'<span class="badge badge-green">● Index ready — {n} chunks</span>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<span class="badge badge-red">● No index — build one above</span>',
            unsafe_allow_html=True,
        )

    st.markdown("---")
    st.markdown("### 💬 Conversation")
    if st.button("🗑️ Clear chat"):
        st.session_state.messages = []
        st.rerun()

    st.markdown("""
    <div style="margin-top:2rem;font-size:11px;color:#00A2FF;line-height:1.8">
    <b style="color:#ffffff">Virtual Pro Software Development</b><br>
    virtualproph.com<br><br>
    <span style="color:#88aacc">Streamlit · OpenAI gpt-4o-mini<br>
    text-embedding-3-small · FAISS</span>
    </div>
    """, unsafe_allow_html=True)

# ── Main chat area ─────────────────────────────────────────────────────────────
st.markdown(
    "<div style='text-align:center;margin-bottom:0.5rem'>"
    "<span style='font-size:13px;font-weight:600;letter-spacing:2px;color:#00A2FF;text-transform:uppercase'>Virtual Pro</span>"
    "</div>"
    "<h2 style='text-align:center;color:#ffffff;font-weight:700;font-family:Open Sans,sans-serif;"
    "margin-bottom:0.25rem'>FAQ Assistant</h2>",
    unsafe_allow_html=True,
)
st.markdown(
    "<p style='text-align:center;color:#00A2FF;font-size:14px;margin-bottom:1.5rem'>"
    "Cost-effective &amp; reliable answers — grounded in your FAQ document.</p>",
    unsafe_allow_html=True,
)

# Render the full conversation history each time the page re-runs
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            with st.expander(f"📎 {len(msg['sources'])} source chunks used"):
                for i, src in enumerate(msg["sources"], 1):
                    st.markdown(
                        f"<div style='font-size:12px;color:#888;padding:6px 0;"
                        f"border-top:1px solid #2a2a30'><b>#{i}</b><br>{src}</div>",
                        unsafe_allow_html=True,
                    )

# Chat input — walrus operator assigns prompt only when the user submits text
if prompt := st.chat_input("Ask a question about our FAQ…"):
    if not DEMO_MODE and not os.getenv("OPENAI_API_KEY"):
        st.error("Add your OpenAI API key in the sidebar.")
    elif not DEMO_MODE and not index_ready():
        st.error("Build the index first using the sidebar.")
    else:
        # Append and render the user's message immediately
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate and stream the assistant's response
        with st.chat_message("assistant"):
            try:
                answer, sources = answer_question(prompt)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": answer,
                    "sources": sources,
                })
                # Show which FAQ chunks were used as sources
                if sources:
                    with st.expander(f"📎 {len(sources)} source chunks used"):
                        for i, src in enumerate(sources, 1):
                            st.markdown(
                                f"<div style='font-size:12px;color:#888;padding:6px 0;"
                                f"border-top:1px solid #2a2a30'><b>#{i}</b><br>{src}</div>",
                                unsafe_allow_html=True,
                            )
            except Exception as e:
                st.error(f"Error: {e}")
